learningDjango/urls.py
from django.contrib import admin
from django.urls import path, include

from pages.views import home_view, contact_view, about_view, social_view

urlpatterns = [
    # pages
    path('', home_view, name='home'),
    path('contact/', contact_view, name='contact'),
    path('about/', about_view, name='about'),
    path('social/', social_view, name='social'),
    path('admin/', admin.site.urls, name='admin'),
    # products
    path('products/', include('products.urls')),
]

products/urls.py
from django.urls import path
from .views import (product_detail_view,
                    render_initial_data,
                    product_create_view,
                    dynamic_lookup_view,
                    product_nice_create_view,
                    product_delete_view,
                    product_list_view, )


app_name = "products"
urlpatterns = [
    path('<int:URLid>/', dynamic_lookup_view, name='products'),
    path('', product_list_view, name='list'),
    path('<int:URLid>/delete', product_delete_view, name='delete'),
    path('product/', product_detail_view, name='product'),
    path('create/', product_create_view, name='create'),
    path('nicecreate/', product_nice_create_view, name='nice_create'),
    path('render/', render_initial_data, name='render'),
]

blog/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=120)  # max_length = required
    description = models.TextField(blank=True, null=True)
    # blank means mot required, null means it can be blank in the database
    price = models.DecimalField(decimal_places=2, max_digits=10000)
    summary = models.TextField(blank=False, null=False)
    featured = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse("products:products", kwargs={"URLid": self.id})  # f"/products/{self.id}"

products/forms.py
# i actually made this file, django didnt give it to me!
from django import forms

from .models import Product


class ProductForm(forms.ModelForm):
    title = forms.CharField(label='', widget=forms.TextInput(attrs={"placeholder": "Your title"}))
    description = forms.CharField(required=False, widget=forms.Textarea(attrs={
        "class": "new-class-name two",
        "placeholder": "Your description",
        "id": "id-for-this-textarea",
        "rows": 10,
        "cols": 35,
    }))
    price = forms.DecimalField(initial=199.99)

    class Meta:
        model = Product
        fields = [
            'title',
            'description',
            'price'
        ]

    def clean_title(self, *args, **kwargs):
        title = self.cleaned_data.get("title")
        if "dick" in title:
            raise forms.ValidationError("This is not a valid title")
        return title


class ProductNiceForm(forms.ModelForm):
    title = forms.CharField(label='', widget=forms.TextInput(attrs={
        "autocomplete": "off",
        "placeholder": " ",
    }))
    description = forms.CharField(label='', required=False, widget=forms.Textarea(attrs={
        "autocomplete": "off",
        "placeholder": " ",
        # "rows": 10,
        # "cols": 35,
    }))
    price = forms.DecimalField(label='', initial=199.99, widget=forms.TextInput(attrs={
        "autocomplete": "off",
        "placeholder": " ",
    }))

    class Meta:
        model = Product
        fields = [
            'title',
            'description',
            'price'
        ]

    def clean_title(self, *args, **kwargs):
        title = self.cleaned_data.get("title")
        if "dick" in title:
            raise forms.ValidationError("This title contains profanity")
        return title

    def clean_description(self, *args, **kwargs):
        description = self.cleaned_data.get("description")
        if "dick" in description:
            raise forms.ValidationError("This description contains profanity")
        return description


class RawProductForm(forms.Form):
    title = forms.CharField(label='', widget=forms.TextInput(attrs={"placeholder": "Your title"}))
    description = forms.CharField(required=False, widget=forms.Textarea(attrs={
        "class": "new-class-name two",
        "placeholder": "Your description",
        "id": "id-for-this-textarea",
        "rows": 10,
        "cols": 35,
    }))
    price = forms.DecimalField(initial=199.99)

blog/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
# from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def home_view(request, *args, **kwargs):
    print(f"args: {args}, kwargs: {kwargs}")
    print("request: ", request.user)
    # return HttpResponse("<h1>Hello World</h1>")
    return render(request, "home.html", {})


def contact_view(request, *args, **kwargs):
    return render(request, "contact.html", {})


def about_view(request, *args, **kwargs):
    my_context = {
        "my_html": "<h1>Render me with safe to use the tags!</h1>",
        "my_text": "This is about us",
        "my_number": 123,
        "my_list": [543, 5467, 122, "five"],
    }
    return render(request, "about.html", my_context)


def social_view(request, *args, **kwargs):
    return render(request, "social.html", {})

products/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect

from .models import Product
from .forms import ProductForm, RawProductForm, ProductNiceForm


# Create your views here.

def product_list_view(request):
    queryset = Product.objects.all()
    context = {
        "object_list": queryset
    }
    return render(request, "products/product_list.html", context)


def product_delete_view(request, URLid):
    obj = get_object_or_404(Product, id=URLid)

    if request.method == "POST":
        # confirming delete
        obj.delete()
        return redirect('/')

    context = {
        "object": obj
    }
    return render(request, "products/product_delete.html", context)


def dynamic_lookup_view(request, URLid):  # URLid comes from urls.py
    # obj = Product.objects.get(id=URLid)
    # obj = get_object_or_404(Product, id=URLid)
    try:
        obj = Product.objects.get(id=URLid)
    except Product.DoesNotExist:
        raise Http404

    context = {
        "object": obj
    }
    return render(request, "products/product_details.html", context)


# Change a product, with initial data
def render_initial_data(request):
    initial_data = {
        'title': "A initial title!"
    }

    obj = Product.objects.get(id=1)
    form = ProductForm(request.POST or None, initial=initial_data, instance=obj)
    if form.is_valid():
        form.save()

    context = {
        'form': form
    }
    return render(request, "products/product_create.html", context)


# Model form
def product_create_view(request):
    form = ProductForm(request.POST or None)  # if POST comes true it renders it
    if form.is_valid():
        form.save()
        form = ProductForm()

    context = {
        'form': form
    }
    return render(request, "products/product_create.html", context)


def product_nice_create_view(request):
    form = ProductNiceForm(request.POST or None)  # if POST comes true it renders it
    if form.is_valid():
        form.save()
        form = ProductNiceForm()

    context = {
        'form': form
    }
    return render(request, "products/product_nice_create.html", context)


# Raw form
# def product_create_view(request):
#     rawForm = RawProductForm()  # Rendering the form (aka instancing from Python)
#     if request.method == "POST":
#         rawForm = RawProductForm(request.POST)  # Rendering the post of the form
#         if rawForm.is_valid():
#             print(rawForm.cleaned_data)
#         else:
#             print(rawForm.errors)
#
#     context = {
#         "form": rawForm
#     }
#     return render(request, "products/product_create.html", context)


# Processing the requests directly w/o form
# def product_create_view(request):
#     # print(request.POST)
#     # print(request.GET)
#     if request.method == "POST":
#         titleGot = request.POST.get('title')
#         print(titleGot)
#         # Product.objects.create(title=titleGot)
#     context = {}
#     return render(request, "products/product_create.html", context)

def product_detail_view(request):
    obj = Product.objects.get(id=1)
    context = {
        # 'title': obj.title,
        # 'description': obj.description,
        'object': obj
    }
    return render(request, "products/product_details.html", context)

products/templates/products/product_create.html
{% extends 'base.html' %}

{% block content %}
<form method="POST"> {% csrf_token %}
    {{ form.as_p }}
{#    <input type="text" name="title" placeholder="Your title"/>#}
    <input type="submit" value="Save"/>
</form>
{% endblock %}

products/templates/products/product_delete.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">{% csrf_token %}
        <h1>Do you want to delete the product "{{ object.title }}"?</h1>
        <p><input type="submit" value="Yes"/></p> <a href="../">Cancel</a>
    </form>
{% endblock %}

products/templates/products/product_details.html
{% extends 'base.html' %}

{% block content %}
    <h1>In App Template: {{ object.title }}</h1>
    <p>
        {% if object.description != None and object.description != ''%} {{ object.description }}
        {% else %} Description Coming soon
        {% endif %}
    </p>
    <p>{{ object.price }}</p>

{% endblock %}

products/templates/products/product_list.html
{% extends 'base.html' %}

{% block content %}
{#{{ object_list }}#}
<h1>Products:</h1>
{% for instance in object_list %}
    <br/><br/>
    <a href="{{ instance.get_absolute_url }}">{{ instance.id }} - {{ instance.title }}</a>
{% endfor %}
{% endblock %}

products/templates/products/product_nice_create.html
{% extends 'base.html' %}
{% load static %}

<head>
    {% block head %}
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>Nicer Product Create Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/nicecreateForm.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/nicecreateFormPopup.css' %}"/>
    {% endblock %}
</head>
<body>
{% block content %}
<div class="box">
    <h2>Create Review</h2>
    <form method="POST"> {% csrf_token %}
        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}

        {% if form.non_field_errors %}
            <div class="" role="alert">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
        {#    TITLE BLOCK    #}
        <div>
            {{ form.title }}
            <label for="{{ form.title.id_for_label }}" class="label-name">
                Title
            </label>
            <div class="popup">
                <span class="popuptext" id="titlePopup">
                    {% if form.title.errors %}
                        {% for error in form.title.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    {% endif %}
                </span>
            </div>
        </div>
        {#    DESCRIPTION BLOCK    #}
        <div>
            {{ form.description }}
            <label for="{{ form.description.id_for_label }}" class="label-name">
                Description
            </label>
            <div class="popup">
                <span class="popuptext" id="descPopup">
                    {% if form.description.errors %}
                        {% for error in form.description.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    {% endif %}
                </span>
            </div>
        </div>
            {#    PRICE BLOCK    #}
        <div>
            {{ form.price }}
            <label for="{{ form.price.id_for_label }}" class="label-name">
                Price
            </label>
            <div class="popup">
                <span class="popuptext" id="pricePopup">
                    {% if form.price.errors %}
                        {% for error in form.price.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    {% endif %}
                </span>
            </div>
        </div>
        <input type="submit" value="Save" id="bottone"/>
    </form>
</div>
    <script>
            {% if form.title.errors %}
                let titlePopup = document.getElementById("titlePopup");
                titlePopup.classList.toggle("show");
            {% endif %}

            {% if form.description.errors %}
                let descPopup = document.getElementById("descPopup");
                descPopup.classList.toggle("show");
            {% endif %}

            {% if form.price.errors %}
                let pricePopup = document.getElementById("pricePopup");
                pricePopup.classList.toggle("show");
            {% endif %}
    </script>
</body>
{% endblock %}

templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h1>About Page</h1>
    <p>Templating!</p>

    {{ my_html|safe }}
    {{ my_html|striptags }}

    <p>
    {{ my_text }}
    {{ my_number }} is a number we like, we also like these numbers: {{ my_list }}<br>
    in a better format:
    </p>
    <ul>
    {% for my_sub_item in my_list %}
        {% if my_sub_item == 122 %}
            <li>{{ forloop.counter }} - {{ my_sub_item }}+22 = {{ my_sub_item|add:22 }}</li>
        {% elif my_sub_item == "five"%}
            <li>{{ forloop.counter }} - six</li>
        {% else %}
            <li>{{ forloop.counter }} - {{ my_sub_item }}</li>
        {% endif %}

    {% endfor %}
    </ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>We are learning django here!</title>
    {% endblock %}
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %} <!-- content is a variable, i can change that no problem-->
        replace me
    {% endblock %}
</body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block content %}
    <h1>Contact Page</h1>
    <p>Templating!</p>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>Home Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>
    {% endblock %}
</head>
{% block content %}
    <h1>Hello World</h1>
    {{ request.user }}
    <p>Templating!</p>
    <p class="testClass">Using static css from django!</p>
{% endblock %}
</html>

templates/navbar.html
<nav>
    <ul>
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'products:list' %}">Products List</a></li>
        <li><a href="{% url 'products:create' %}">Create Product</a></li>
        <li><a href="{% url 'products:nice_create' %}">Create Nice Product</a></li>
        <li><a href="{% url 'contact' %}">Contact</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
    </ul>
</nav>

templates/social.html
{% extends 'base.html' %}

{% block content %}
    <h1>Social Page</h1>
    <p>Templating!</p>
{% endblock%}